# Generated by Django 5.1.7 on 2025-04-16 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_date', models.DateField(blank=True, null=True, verbose_name='Data de criação original')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de upload')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Autor/Fotógrafo')),
                ('copyright', models.CharField(blank=True, max_length=255, verbose_name='Direitos autorais/Licença')),
                ('keywords', models.CharField(blank=True, max_length=512, verbose_name='Palavras-chave/Tags')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('dpi', models.CharField(blank=True, max_length=32)),
                ('file_format', models.CharField(blank=True, max_length=16)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('bit_depth', models.CharField(blank=True, max_length=16)),
                ('color_mode', models.CharField(blank=True, max_length=32)),
                ('color_profile', models.CharField(blank=True, max_length=255)),
                ('collection', models.CharField(blank=True, max_length=255, verbose_name='Coleção/Acervo')),
                ('catalog_number', models.CharField(blank=True, max_length=128, verbose_name='Número de catalogação')),
                ('physical_location', models.CharField(blank=True, max_length=255, verbose_name='Localização física')),
                ('provenance', models.CharField(blank=True, max_length=255, verbose_name='Proveniência')),
                ('cross_reference', models.CharField(blank=True, max_length=255, verbose_name='Referência cruzada')),
                ('exif_data', models.JSONField(blank=True, null=True, verbose_name='Dados EXIF')),
                ('geolocation', models.CharField(blank=True, max_length=255, verbose_name='Informações geográficas/geolocalização')),
                ('file', models.ImageField(upload_to='uploads/images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(blank=True, max_length=255, verbose_name='Autor(es)')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Assunto/Tema')),
                ('description', models.TextField(blank=True, verbose_name='Descrição/Resumo')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Data de criação')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Data de publicação')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Editora/Publicador')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Versão/Edição')),
                ('languages', models.CharField(blank=True, max_length=128, verbose_name='Idioma(s)')),
                ('keywords', models.CharField(blank=True, max_length=512, verbose_name='Palavras-chave/Tags')),
                ('doc_type', models.CharField(blank=True, choices=[('artigo', 'Artigo'), ('relatorio', 'Relatório'), ('livro', 'Livro'), ('monografia', 'Monografia'), ('tese', 'Tese'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de documento')),
                ('file', models.FileField(upload_to='uploads/documents/')),
                ('file_format', models.CharField(blank=True, max_length=16, verbose_name='Formato do arquivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do arquivo (bytes)')),
                ('num_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de páginas')),
                ('orientation', models.CharField(blank=True, max_length=16, verbose_name='Orientação')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texto extraído para indexação')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='images.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/audios/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='images.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/video_thumbs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='images.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
