# Generated by Django 5.1.7 on 2025-04-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_460',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/images/460/'),
        ),
    ]
