# Generated by Django 5.1.7 on 2025-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_original_filename_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGridConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_columns', models.PositiveSmallIntegerField(choices=[(1, '1 coluna'), (2, '2 colunas'), (3, '3 colunas'), (4, '4 colunas'), (6, '6 colunas')], default=4)),
            ],
            options={
                'verbose_name': 'Configuração da Grid de Imagens',
                'verbose_name_plural': 'Configurações da Grid de Imagens',
            },
        ),
    ]
