# Generated by Django 5.1.7 on 2025-04-20 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_imagegridconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='images.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curtida',
                'verbose_name_plural': 'Curtidas',
                'unique_together': {('user', 'image')},
            },
        ),
        migrations.DeleteModel(
            name='ImageGridConfig',
        ),
    ]
