version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: libraryvault
      POSTGRES_USER: libraryvault
      POSTGRES_PASSWORD: libraryvault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  weaviate:
    image: semitechnologies/weaviate:1.19.10
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
    ports:
      - "8080:8080"
volumes:
  pgdata:
  minio_data:
