# Generated by Django 5.1.7 on 2025-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagination_items_per_page', models.PositiveIntegerField(default=15, verbose_name='Itens por página (global)')),
                ('report_types', models.TextField(blank=True, verbose_name='Tipos de relatórios (um por linha)')),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
    ]
