# Generated by Django 5.1.7 on 2025-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='report_menu_links',
            field=models.TextField(blank=True, verbose_name='Relatórios no menu (um por linha: Nome|URL)'),
        ),
    ]
