# Generated by Django 5.1.7 on 2025-04-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_globalconfig_report_menu_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_per_page', models.PositiveIntegerField(default=15, verbose_name='Itens por página')),
                ('pagination_visible_pages', models.PositiveIntegerField(default=5, verbose_name='Páginas visíveis na paginação')),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
        migrations.DeleteModel(
            name='GlobalConfig',
        ),
    ]
